# Generated by Django 5.1.6 on 2025-10-28 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 28, 17, 50, 25, 565785, tzinfo=datetime.timezone.utc)),
        ),
    ]
