# Generated by Django 5.1.6 on 2025-10-23 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_otp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 23, 9, 31, 0, 47169, tzinfo=datetime.timezone.utc)),
        ),
    ]
