# Generated by Django 5.1.6 on 2025-10-28 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_otp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 28, 18, 11, 49, 924171, tzinfo=datetime.timezone.utc)),
        ),
    ]
