# Generated by Django 5.1.6 on 2025-10-23 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_otp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 23, 9, 34, 25, 695217, tzinfo=datetime.timezone.utc)),
        ),
    ]
