# Generated by Django 5.1.6 on 2025-11-06 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_otp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 6, 11, 46, 56, 160269, tzinfo=datetime.timezone.utc)),
        ),
    ]
