# Generated by Django 5.1.6 on 2025-11-08 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_otp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 8, 11, 34, 34, 792643, tzinfo=datetime.timezone.utc)),
        ),
    ]
