# Generated by Django 5.1.4 on 2025-02-12 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0007_remove_order_address_order_address_line1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 12, 6, 42, 7, 468761, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
