# Generated by Django 5.1.1 on 2025-01-07 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0007_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 7, 9, 59, 52, 500338, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
