# Generated by Django 5.1.6 on 2025-11-08 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_otp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 8, 11, 35, 39, 154296, tzinfo=datetime.timezone.utc)),
        ),
    ]
