# Generated by Django 5.1.4 on 2025-01-18 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0008_variant_is_active_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 18, 7, 56, 33, 555301, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
