# Generated by Django 5.1.4 on 2025-01-20 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0009_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 20, 4, 38, 0, 204900, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
