# Generated by Django 5.1.4 on 2025-01-20 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0010_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 20, 4, 47, 1, 455422, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
