# Generated by Django 5.1.4 on 2025-01-20 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0011_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="is_deleted",
        ),
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 20, 9, 41, 52, 110141, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
