# Generated by Django 5.1.6 on 2025-11-24 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_alter_review_unique_together_review_helpful_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 24, 1, 36, 37, 863920, tzinfo=datetime.timezone.utc)),
        ),
    ]
