# Generated by Django 5.1.4 on 2025-02-14 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0013_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 14, 4, 56, 57, 712685, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
