# Generated by Django 5.1.6 on 2025-11-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_otp_expiration_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_approved', '-created_at'], name='manager_rev_product_d8f8d4_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_approved', '-helpful_count'], name='manager_rev_product_244199_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_approved', 'rating'], name='manager_rev_product_ba28bd_idx'),
        ),
    ]
