# Generated by Django 5.1.4 on 2025-01-24 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0015_alter_otp_expiration_time_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 24, 10, 4, 38, 581508, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
