# Generated by Django 5.1.4 on 2025-02-21 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0015_coupon_alter_otp_expiration_time_couponusage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 21, 11, 52, 5, 813686, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
