# Generated by Django 5.1.4 on 2025-01-24 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0016_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 24, 20, 45, 9, 533348, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
