# Generated by Django 5.1.4 on 2025-01-25 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0018_address_is_deleted_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Addresses"},
        ),
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 25, 5, 27, 27, 990235, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
