# Generated by Django 5.1.4 on 2025-02-24 13:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_remove_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='order',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='manager.orderitem'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 13, 42, 52, 319353, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('defective', 'Product Defective'), ('wrong_item', 'Wrong Item Received'), ('not_as_described', 'Item Not As Described'), ('size_issue', 'Size/Fit Issue'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('REFUND', 'Refund'), ('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='manager.wallet')),
            ],
        ),
    ]
