# Generated by Django 5.1.4 on 2025-01-25 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0021_paymentmethod_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 25, 13, 31, 0, 930467, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
