# Generated by Django 5.1.4 on 2025-02-25 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_orderitem_admin_response_orderitem_return_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='admin_response',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='return_status',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 7, 24, 44, 787345, tzinfo=datetime.timezone.utc)),
        ),
    ]
