# Generated by Django 5.1.4 on 2025-01-26 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0023_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 26, 9, 5, 39, 765004, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
