# Generated by Django 5.1.4 on 2025-02-25 07:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_remove_orderitem_admin_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.order'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(default='SUCCESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 7, 39, 12, 345306, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('REFUND', 'Refund')], max_length=10),
        ),
    ]
