# Generated by Django 5.1.6 on 2025-02-27 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_referraloffer_alter_otp_expiration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 13, 9, 30, 726455, tzinfo=datetime.timezone.utc)),
        ),
    ]
