# Generated by Django 5.1.6 on 2025-08-27 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_alter_otp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 5, 25, 6, 441680, tzinfo=datetime.timezone.utc)),
        ),
    ]
