# Generated by Django 5.1.6 on 2025-08-27 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_alter_otp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 6, 24, 23, 224141, tzinfo=datetime.timezone.utc)),
        ),
    ]
