# Generated by Django 5.1.6 on 2025-10-22 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_alter_otp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 9, 43, 3, 23278, tzinfo=datetime.timezone.utc)),
        ),
    ]
