# Generated by Django 5.1.4 on 2025-01-27 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0031_orderitem_product_name_alter_orderitem_variant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 27, 1, 46, 46, 389030, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
