# Generated by Django 5.1.6 on 2025-03-18 03:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_order_added_date_order_is_active_order_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='manager.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 3, 53, 40, 380473, tzinfo=datetime.timezone.utc)),
        ),
    ]
