# Generated by Django 5.1.4 on 2025-01-27 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0032_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 27, 1, 47, 37, 992278, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
