# Generated by Django 5.1.6 on 2025-03-18 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_alter_order_payment_method_alter_otp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 3, 55, 55, 997416, tzinfo=datetime.timezone.utc)),
        ),
    ]
