# Generated by Django 5.1.6 on 2025-03-18 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0035_alter_otp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 4, 17, 31, 857675, tzinfo=datetime.timezone.utc)),
        ),
    ]
