# Generated by Django 5.1.6 on 2025-03-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_remove_duplicate_product_discount'),
        ('manager', '0037_alter_otp_expiration_time'),
    ]

    operations = [
    ]
