# Generated by Django 5.1.4 on 2025-01-28 06:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0039_remove_order_billing_address_remove_order_cart_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paymentmethod",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manager.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 28, 6, 26, 55, 701198, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
