# Generated by Django 5.1.6 on 2025-03-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_orderstatushistory'),
        ('manager', '0040_add_product_discount'),
    ]

    operations = [
    ]
