# Generated by Django 5.1.4 on 2025-01-28 06:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0040_order_paymentmethod_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.product",
            ),
        ),
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 28, 6, 36, 51, 382895, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
