# Generated by Django 5.1.4 on 2025-01-28 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0041_cartitem_product_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="added_date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="order",
            name="updated_date",
        ),
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 28, 7, 53, 16, 962218, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
