# Generated by Django 5.1.6 on 2025-04-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_add_payment_tracking_fields'),
        ('manager', '0041_merge_20250324_1105'),
    ]

    operations = [
    ]
