# Generated by Django 5.1.6 on 2025-04-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0040_add_payment_failure_tracking'),
        ('manager', '0042_merge_20250401_1458'),
    ]

    operations = [
    ]
