# Generated by Django 5.1.6 on 2025-04-01 11:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0043_merge_20250401_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('PAYMENT_PENDING', 'Payment Pending'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 1, 11, 20, 51, 767944, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='manager.orderitem'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=100),
        ),
    ]
