# Generated by Django 5.1.4 on 2025-01-28 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0044_alter_address_added_date_alter_cart_added_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 28, 22, 19, 54, 119499, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
