# Generated by Django 5.1.6 on 2025-04-01 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0045_alter_otp_expiration_time_alter_returnrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 1, 11, 29, 25, 283578, tzinfo=datetime.timezone.utc)),
        ),
    ]
