# Generated by Django 5.1.6 on 2025-04-02 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0046_alter_otp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 8, 45, 5, 570363, tzinfo=datetime.timezone.utc)),
        ),
    ]
