# Generated by Django 5.1.4 on 2025-01-29 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0047_alter_otp_expiration_time_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="size",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 29, 6, 11, 47, 509715, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
