# Generated by Django 5.1.4 on 2025-01-29 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0048_size_stock_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 29, 11, 39, 31, 385761, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
