# Generated by Django 5.1.6 on 2025-04-03 14:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0048_alter_otp_expiration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 3, 14, 18, 24, 228267, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='AdminResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response_type', models.CharField(choices=[('INFO', 'Information'), ('STATUS_UPDATE', 'Status Update'), ('RETURN', 'Return Response'), ('CANCELLATION', 'Cancellation Response')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_responses', to='manager.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='admin_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to='manager.adminresponse'),
        ),
    ]
