# Generated by Django 5.1.6 on 2025-04-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0049_alter_otp_expiration_time_adminresponse_and_more'),
    ]

    operations = [
    ]
