# Generated by Django 5.1.4 on 2025-01-29 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0049_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 29, 12, 59, 3, 759007, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
