# Generated by Django 5.1.4 on 2025-01-29 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0050_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 29, 13, 0, 9, 802652, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
