# Generated by Django 5.1.6 on 2025-04-04 03:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0050_auto_20250403_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 4, 3, 58, 48, 754719, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='admin_response',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='manager.adminresponse'),
            preserve_default=False,
        ),
    ]
