# Generated by Django 5.1.6 on 2025-04-04 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0051_alter_otp_expiration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 4, 4, 4, 36, 118959, tzinfo=datetime.timezone.utc)),
        ),
        # Skip the admin_response field change in this migration
        # We'll handle it in a separate migration
    ]
