# Generated by Django 5.1.6 on 2025-04-04 04:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0052_alter_otp_expiration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 4, 4, 15, 49, 672061, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='admin_response',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='manager.adminresponse'),
            preserve_default=False,
        ),
    ]
