# Generated by Django 5.1.4 on 2025-01-30 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0052_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 30, 9, 58, 21, 475651, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
