# Generated by Django 5.1.4 on 2025-01-30 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0056_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 30, 14, 11, 29, 383301, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
