# Generated by Django 5.1.6 on 2025-04-17 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0057_alter_order_order_id_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 17, 12, 44, 11, 803729, tzinfo=datetime.timezone.utc)),
        ),
    ]
