# Generated by Django 5.1.4 on 2025-01-30 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0057_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 30, 14, 28, 12, 413595, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
