# Generated by Django 5.1.4 on 2025-01-31 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0059_alter_otp_expiration_time_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 31, 21, 39, 54, 606574, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
