# Generated by Django 5.1.6 on 2025-04-23 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0059_remove_cartitem_product_order_payment_expiry_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 23, 20, 31, 57, 40690, tzinfo=datetime.timezone.utc)),
        ),
    ]
