# Generated by Django 5.1.4 on 2025-02-01 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0061_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 1, 13, 55, 7, 170748, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
