# Generated by Django 5.1.4 on 2025-02-02 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0062_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 2, 23, 59, 17, 411050, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
