# Generated by Django 5.1.4 on 2025-02-03 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0063_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 3, 2, 46, 16, 190890, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
