# Generated by Django 5.1.4 on 2025-02-05 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0065_alter_otp_expiration_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 5, 10, 35, 29, 76009, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
