# Generated by Django 5.1.4 on 2025-02-05 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0067_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 5, 10, 36, 29, 666503, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
