# Generated by Django 5.1.4 on 2025-02-06 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0071_remove_size_stock_alter_otp_expiration_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="size",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 6, 15, 4, 25, 147302, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
