# Generated by Django 5.1.4 on 2025-02-09 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0073_remove_variant_stock_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 9, 15, 52, 59, 913785, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
