# Generated by Django 5.1.4 on 2025-02-09 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0074_variant_stock_alter_otp_expiration_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variant",
            name="stock",
        ),
        migrations.AlterField(
            model_name="otp",
            name="expiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 9, 21, 52, 30, 339339, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
